"""empty message

Revision ID: 5b3330b2aaf2
Revises: 
Create Date: 2024-10-01 18:58:52.094128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3330b2aaf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('attendee_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'attendees', ['attendee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'attendee_id')
    # ### end Alembic commands ###
