"""empty message

Revision ID: 7d98bb9bc3f5
Revises: 7c05eb4a723a
Create Date: 2024-10-15 07:33:18.935340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d98bb9bc3f5'
down_revision: Union[str, None] = '7c05eb4a723a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'date',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('events', 'date',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('bookings', 'date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
